import type { LiveCompetition } from "@/lib/competitions/types";

function slugFromId(id: string) {
  return Buffer.from(id, "utf8").toString("base64url");
}

function item(value: Omit<LiveCompetition, "slug">): LiveCompetition {
  return { ...value, slug: slugFromId(value.id) };
}

export const VERIFIED_COMPETITION_CATALOG_2026: LiveCompetition[] = [
  item({
    id: "obm-2026",
    name: "48ª Olimpíada Brasileira de Matemática (OBM)",
    organizer: "Associação Olimpíada Brasileira de Matemática",
    description: "Competição nacional de matemática que também integra o processo de seleção para olimpíadas internacionais.",
    type: "Olimpíada",
    areas: ["Matemática", "Ciência"],
    targetAudience: ["Ensino Fundamental", "Ensino Médio", "Ensino Superior"],
    participation: "Individual",
    scope: "Nacional",
    format: "Presencial",
    modalities: ["Matemática", "Raciocínio Lógico"],
    minAge: null,
    maxAge: null,
    eligibility: "Participantes convocados conforme critérios da OBM 2026, em níveis do Ensino Fundamental, Médio e universitário.",
    city: "Brasil",
    state: "",
    country: "Brasil",
    level: "Nacional",
    stages: ["Convocação", "Confirmação", "Provas nacionais"],
    registrationStart: "2026-09-07",
    registrationEnd: "2026-10-02",
    eventDate: "2026-10-08",
    officialUrl: "https://www.obm.org.br/informacoes-gerais/calendario",
    registrationUrl: "https://www.obm.org.br/informacoes-gerais/calendario",
    regulationUrl: "https://www.obm.org.br/informacoes-gerais/regulamento/",
    sourceName: "OBM — calendário e regulamento oficiais",
    evidence: "Calendário oficial 2026 com confirmação dos convocados até 02/10 e provas em 08 e 09/10/2026.",
    confidence: 100,
    status: "OPEN",
    free: null,
    task: "Resolver provas de matemática de acordo com o nível da competição.",
    prize: "Medalhas, menções e possibilidade de integração em processos de seleção para competições internacionais.",
  }),
  item({
    id: "obmep-2026",
    name: "21ª OBMEP 2026",
    organizer: "Instituto de Matemática Pura e Aplicada (IMPA)",
    description: "Olimpíada nacional de matemática para estudantes da educação básica de escolas públicas e privadas.",
    type: "Olimpíada",
    areas: ["Matemática"],
    targetAudience: ["Ensino Fundamental", "Ensino Médio"],
    participation: "Individual",
    scope: "Nacional",
    format: "Presencial",
    modalities: ["Matemática"],
    minAge: null,
    maxAge: null,
    eligibility: "Estudantes elegíveis inscritos por suas escolas conforme o regulamento da OBMEP 2026.",
    city: "Brasil",
    state: "",
    country: "Brasil",
    level: "Nacional",
    stages: ["Inscrição escolar", "1ª fase", "2ª fase", "Premiação"],
    registrationStart: "2026-02-04",
    registrationEnd: "2026-03-16",
    eventDate: null,
    officialUrl: "https://www.obmep.org.br/regulamento.htm",
    registrationUrl: "https://www.obmep.org.br/",
    regulationUrl: "https://www.obmep.org.br/regulamento.htm",
    sourceName: "OBMEP — regulamento oficial 2026",
    evidence: "Regulamento oficial da 21ª OBMEP informa inscrições de 04/02 a 16/03/2026 e a 1ª fase em 09/06.",
    confidence: 100,
    status: "CLOSED",
    free: null,
    task: "Resolver provas de matemática em duas fases.",
    prize: "Medalhas, menções honrosas e programas acadêmicos associados, conforme regulamento.",
  }),
  item({
    id: "obf-2026",
    name: "Olimpíada Brasileira de Física (OBF) 2026",
    organizer: "Sociedade Brasileira de Física",
    description: "Competição nacional de física para estudantes da educação básica.",
    type: "Olimpíada",
    areas: ["Física", "Ciência"],
    targetAudience: ["Ensino Fundamental", "Ensino Médio"],
    participation: "Individual",
    scope: "Nacional",
    format: "Híbrida",
    modalities: ["Física"],
    minAge: null,
    maxAge: null,
    eligibility: "Estudantes inscritos por escolas conforme categorias e regras da OBF 2026.",
    city: "Brasil",
    state: "",
    country: "Brasil",
    level: "Nacional",
    stages: ["Inscrição", "1ª fase", "Fases seguintes", "Premiação"],
    registrationStart: "2026-04-07",
    registrationEnd: "2026-06-12",
    eventDate: "2026-06-19",
    officialUrl: "https://www1.fisica.org.br/olimpiada/2026/index.php/calendario",
    registrationUrl: "https://app.graxaim.org/obf/2026",
    regulationUrl: "https://www1.fisica.org.br/olimpiada/2026/",
    sourceName: "OBF — calendário oficial 2026",
    evidence: "Calendário oficial informa inscrições até 12/06/2026 e primeira fase em 19 e 20/06.",
    confidence: 100,
    status: "CLOSED",
    free: null,
    task: "Resolver problemas e provas de física conforme o nível.",
    prize: "Medalhas e reconhecimento acadêmico conforme desempenho.",
  }),
  item({
    id: "obi-2026",
    name: "Olimpíada Brasileira de Informática (OBI) 2026",
    organizer: "Instituto de Computação da Unicamp",
    description: "Competição nacional de lógica e programação com modalidades adequadas a diferentes níveis.",
    type: "Olimpíada",
    areas: ["Programação", "Computação", "Tecnologia"],
    targetAudience: ["Ensino Fundamental", "Ensino Médio"],
    participation: "Individual",
    scope: "Nacional",
    format: "Híbrida",
    modalities: ["Programação", "Iniciação", "Computação"],
    minAge: null,
    maxAge: null,
    eligibility: "Estudantes enquadrados nas modalidades e níveis definidos pela OBI.",
    city: "Brasil",
    state: "",
    country: "Brasil",
    level: "Nacional",
    stages: ["Fases classificatórias", "Fase nacional", "Semana Olímpica"],
    registrationStart: null,
    registrationEnd: null,
    eventDate: null,
    officialUrl: "https://olimpiada.ic.unicamp.br/",
    registrationUrl: "https://olimpiada.ic.unicamp.br/",
    regulationUrl: "https://olimpiada.ic.unicamp.br/",
    sourceName: "OBI — site oficial da Unicamp",
    evidence: "Site oficial da OBI 2026 com informações da competição, modalidades, cursos e calendário da temporada.",
    confidence: 95,
    status: "UNKNOWN",
    free: null,
    task: "Resolver desafios de lógica e programação de acordo com a modalidade.",
    prize: "Medalhas, certificados e convites para atividades de formação conforme classificação.",
  }),
  item({
    id: "obq-2026",
    name: "Olimpíada Brasileira de Química (OBQ) 2026",
    organizer: "Programa Nacional Olimpíadas de Química / ABQ",
    description: "Olimpíada nacional de química voltada a estudantes do ensino médio.",
    type: "Olimpíada",
    areas: ["Química", "Ciência"],
    targetAudience: ["Ensino Médio"],
    participation: "Individual",
    scope: "Nacional",
    format: "Presencial",
    modalities: ["Química"],
    minAge: null,
    maxAge: null,
    eligibility: "Estudantes classificados por olimpíadas estaduais vinculadas ao Programa Nacional Olimpíadas de Química.",
    city: "Brasil",
    state: "",
    country: "Brasil",
    level: "Nacional",
    stages: ["Etapas estaduais", "OBQ nacional", "Seletivas internacionais"],
    registrationStart: null,
    registrationEnd: null,
    eventDate: null,
    officialUrl: "https://obquimica.org/olimpiada/olimpiada-brasileira-de-quimica",
    registrationUrl: "https://obquimica.org/",
    regulationUrl: "https://obquimica.org/olimpiada/olimpiada-brasileira-de-quimica",
    sourceName: "Programa Nacional Olimpíadas de Química",
    evidence: "Página oficial contém o regulamento da OBQ 2026 e explica o processo de participação via olimpíadas estaduais.",
    confidence: 100,
    status: "UNKNOWN",
    free: null,
    task: "Realizar exames teóricos e, nas seletivas aplicáveis, atividades práticas de química.",
    prize: "Medalhas e possibilidade de convocação para seletivas internacionais.",
  }),
  item({
    id: "obb-2026",
    name: "XXII Olimpíada Brasileira de Biologia (OBB) 2026",
    organizer: "Instituto Butantan",
    description: "Competição nacional de biologia com fases classificatórias e seletivas para olimpíadas internacionais.",
    type: "Olimpíada",
    areas: ["Biologia", "Ciência", "Biotecnologia"],
    targetAudience: ["Ensino Médio"],
    participation: "Individual",
    scope: "Nacional",
    format: "Híbrida",
    modalities: ["Biologia"],
    minAge: null,
    maxAge: null,
    eligibility: "Estudantes elegíveis inscritos por suas escolas conforme regras da OBB 2026.",
    city: "Brasil",
    state: "",
    country: "Brasil",
    level: "Nacional",
    stages: ["Inscrição", "Fase 1", "Fase 2", "Fase 3", "Seletivas internacionais"],
    registrationStart: "2026-01-15",
    registrationEnd: "2026-02-25",
    eventDate: "2026-03-03",
    officialUrl: "https://olimpiadasdebiologia.butantan.gov.br/cronograma",
    registrationUrl: "https://olimpiadasdebiologia.butantan.gov.br/",
    regulationUrl: "https://olimpiadasdebiologia.butantan.gov.br/fases-e-inscricoes",
    sourceName: "Instituto Butantan — OBB",
    evidence: "Cronograma oficial registra inscrições de 15/01 a 25/02/2026 e início das provas em março.",
    confidence: 100,
    status: "CLOSED",
    free: null,
    task: "Resolver avaliações de biologia e participar das fases seletivas conforme classificação.",
    prize: "Medalhas e vagas para processos seletivos das olimpíadas internacionais de biologia.",
  }),
  item({
    id: "obg-2026",
    name: "11ª Olimpíada Brasileira de Geografia (OBG) 2026",
    organizer: "Comissão Organizadora da OBG",
    description: "Olimpíada nacional de geografia em equipes, com fases online e final presencial.",
    type: "Olimpíada",
    areas: ["Geografia", "Ciência", "Meio ambiente"],
    targetAudience: ["Ensino Fundamental", "Ensino Médio"],
    participation: "Equipe",
    scope: "Nacional",
    format: "Híbrida",
    modalities: ["Geografia", "Ciências Humanas"],
    minAge: null,
    maxAge: null,
    eligibility: "Equipes de 3 estudantes do 9º ano do Ensino Fundamental ao 3º/4º ano do Ensino Médio, da mesma instituição.",
    city: "Brasil",
    state: "",
    country: "Brasil",
    level: "Nacional",
    stages: ["3 fases online", "Final presencial nacional", "Possível seleção internacional"],
    registrationStart: null,
    registrationEnd: "2026-07-20",
    eventDate: "2026-11-23",
    officialUrl: "https://obgeografia.com.br/",
    registrationUrl: "https://obgeografia.com.br/",
    regulationUrl: "https://obgeografia.com.br/regulamento/",
    sourceName: "OBG — site e regulamento oficiais",
    evidence: "Site oficial informa inscrições prorrogadas até 20/07/2026 e fase presencial nacional de 23 a 27/11/2026.",
    confidence: 100,
    status: "CLOSED",
    free: null,
    task: "Resolver desafios de geografia e análise espacial em equipe.",
    prize: "Medalhas, certificados e possibilidade de participação em fase internacional.",
  }),
  item({
    id: "onc-2026",
    name: "Olimpíada Nacional de Ciências (ONC) 2026",
    organizer: "UFPI / MCTI e instituições científicas parceiras",
    description: "Olimpíada interdisciplinar de ciências para estudantes do Ensino Fundamental e Médio.",
    type: "Olimpíada",
    areas: ["Física", "Química", "Biologia", "Astronomia", "História", "Ciência"],
    targetAudience: ["Ensino Fundamental", "Ensino Médio"],
    participation: "Individual",
    scope: "Nacional",
    format: "Online",
    modalities: ["Ciências", "Física", "Química", "Biologia", "Astronomia", "História"],
    minAge: null,
    maxAge: null,
    eligibility: "Estudantes do Ensino Fundamental e Médio conforme categorias do regulamento.",
    city: "Online",
    state: "",
    country: "Brasil",
    level: "Nacional",
    stages: ["Inscrição", "1ª fase", "2ª fase", "Premiação"],
    registrationStart: null,
    registrationEnd: "2026-08-24",
    eventDate: "2026-08-27",
    officialUrl: "https://onciencias.org/",
    registrationUrl: "https://onciencias.org/",
    regulationUrl: "https://www.onciencias.org/regulamento",
    sourceName: "ONC — site oficial",
    evidence: "Calendário oficial informa inscrições até 24/08, primeira fase de 27 a 29/08 e segunda fase em 17 e 18/09/2026.",
    confidence: 100,
    status: "CLOSED",
    free: true,
    task: "Resolver desafios interdisciplinares de ciências.",
    prize: "Medalhas e reconhecimento nacional conforme classificação.",
  }),
  item({
    id: "onee-2026",
    name: "Olimpíada Nacional de Eficiência Energética (ONEE) 2026",
    organizer: "ANEEL / iABRADEE / distribuidoras de energia",
    description: "Competição educacional sobre eficiência energética, sustentabilidade e consumo consciente.",
    type: "Olimpíada",
    areas: ["Energia", "Sustentabilidade", "Tecnologia", "Meio ambiente"],
    targetAudience: ["Ensino Fundamental", "Ensino Médio"],
    participation: "Individual",
    scope: "Nacional",
    format: "Híbrida",
    modalities: ["Eficiência Energética", "Sustentabilidade", "Games", "Ciência"],
    minAge: null,
    maxAge: null,
    eligibility: "Estudantes do 8º e 9º anos do Ensino Fundamental e do 1º e 2º anos do Ensino Médio em escolas participantes.",
    city: "Brasília",
    state: "DF",
    country: "Brasil",
    level: "Nacional",
    stages: ["Inscrição", "Trilha e games", "Provas", "Semana Olímpica", "Premiação"],
    registrationStart: "2026-06-08",
    registrationEnd: "2026-09-15",
    eventDate: "2026-11-03",
    officialUrl: "https://onee.org.br/",
    registrationUrl: "https://onee.org.br/",
    regulationUrl: "https://www.onee.org.br/regulamento/",
    sourceName: "ONEE / ANEEL — fontes oficiais",
    evidence: "Site oficial informa inscrições de 08/06 a 15/09/2026 e Semana Olímpica em novembro.",
    confidence: 100,
    status: "CLOSED",
    free: true,
    task: "Participar de trilha educativa, games e provas sobre eficiência energética.",
    prize: "Premiações nacionais e reconhecimento de estudantes e professores conforme regulamento.",
  }),
  item({
    id: "fecti-2026",
    name: "XX FECTI 2026 — Feira de Ciência, Tecnologia e Inovação do Estado do Rio de Janeiro",
    organizer: "Fundação Cecierj",
    description: "Feira estadual de ciência, tecnologia e inovação para projetos estudantis do Rio de Janeiro.",
    type: "Feira",
    areas: ["Ciência", "Tecnologia", "Inovação", "Engenharia"],
    targetAudience: ["Ensino Fundamental", "Ensino Médio", "Ensino Técnico"],
    participation: "Equipe",
    scope: "Estadual",
    format: "Presencial",
    modalities: ["Projetos Científicos", "Tecnologia", "Inovação"],
    minAge: null,
    maxAge: null,
    eligibility: "Projetos de estudantes conforme categorias e regulamento da FECTI.",
    city: "Rio de Janeiro",
    state: "RJ",
    country: "Brasil",
    level: "Estadual",
    stages: ["Inscrição de projetos", "Avaliação", "Mostra"],
    registrationStart: "2026-07-10",
    registrationEnd: "2026-09-15",
    eventDate: null,
    officialUrl: "https://fecti.cecierj.edu.br/login",
    registrationUrl: "https://fecti.cecierj.edu.br/login",
    regulationUrl: "https://fecti.cecierj.edu.br/login",
    sourceName: "Fundação Cecierj — SisFECTI",
    evidence: "A plataforma oficial informa inscrições para a XX FECTI de 10/07 a 15/09/2026.",
    confidence: 100,
    status: "CLOSED",
    free: null,
    task: "Submeter e apresentar projeto científico ou tecnológico conforme regulamento.",
    prize: "Premiações e credenciamento para oportunidades científicas conforme edição.",
  }),
  item({
    id: "febic-2026",
    name: "XI FEBIC 2026 — Feira Brasileira de Iniciação Científica",
    organizer: "Instituto Brasileiro de Iniciação Científica (IBIC)",
    description: "Feira nacional para apresentação de projetos científicos, tecnológicos e relatos de experiência.",
    type: "Feira",
    areas: ["Ciência", "Tecnologia", "Inovação", "Pesquisa"],
    targetAudience: ["Ensino Fundamental", "Ensino Médio", "Ensino Técnico", "Ensino Superior"],
    participation: "Equipe",
    scope: "Nacional",
    format: "Híbrida",
    modalities: ["Pesquisa", "Projetos", "Iniciação Científica"],
    minAge: null,
    maxAge: null,
    eligibility: "Projetos e relatos conforme categorias do regulamento da FEBIC 2026.",
    city: "Jaraguá do Sul",
    state: "SC",
    country: "Brasil",
    level: "Nacional",
    stages: ["Inscrição", "Seleção", "Avaliação remota", "Etapa presencial"],
    registrationStart: "2026-02-23",
    registrationEnd: "2026-04-24",
    eventDate: "2026-09-14",
    officialUrl: "https://www.ibicsc.com.br/public/febic.php",
    registrationUrl: "https://www.ibicsc.com.br/public/febic.php",
    regulationUrl: "https://www.ibicsc.com.br/paginas/febic.php",
    sourceName: "IBIC — FEBIC",
    evidence: "Timeline oficial informa inscrições de 23/02 a 24/04 e etapa presencial de 14 a 18/09/2026.",
    confidence: 100,
    status: "CLOSED",
    free: null,
    task: "Submeter projeto ou relato e apresentar o trabalho nas etapas da feira.",
    prize: "Premiações, certificados e credenciamentos conforme regulamento.",
  }),
  item({
    id: "desafio-liga-jovem-2026",
    name: "Desafio Liga Jovem 4 — 2026",
    organizer: "Sebrae",
    description: "Competição nacional de empreendedorismo de impacto para estudantes da educação básica e profissional.",
    type: "Desafio",
    areas: ["Empreendedorismo", "Inovação", "Impacto Social", "Sustentabilidade"],
    targetAudience: ["Ensino Fundamental", "Ensino Médio", "Ensino Técnico"],
    participation: "Equipe",
    scope: "Nacional",
    format: "Híbrida",
    modalities: ["Empreendedorismo", "Inovação", "Projetos"],
    minAge: null,
    maxAge: null,
    eligibility: "Equipes de 2 a 5 estudantes do 8º/9º ano, Ensino Médio, Técnico, Profissional ou Tecnológico, com professor orientador.",
    city: "Brasil",
    state: "",
    country: "Brasil",
    level: "Nacional",
    stages: ["Inscrição", "Etapas estaduais", "Semifinal", "Final"],
    registrationStart: null,
    registrationEnd: "2026-05-28",
    eventDate: null,
    officialUrl: "https://www.desafioligajovem.com.br/",
    registrationUrl: "https://inscricao.desafioligajovem.com.br/",
    regulationUrl: "https://www.desafioligajovem.com.br/",
    sourceName: "Desafio Liga Jovem — site oficial",
    evidence: "Site oficial informa inscrições encerradas em 28/05/2026 e etapas estaduais em andamento.",
    confidence: 100,
    status: "CLOSED",
    free: true,
    task: "Criar, desenvolver e apresentar uma solução para um problema real.",
    prize: "Premiação total anunciada de até R$ 600 mil em prêmios e experiências, conforme a edição.",
  }),
  item({
    id: "onda",
    name: "ONDA — Olimpíada Nacional de Aplicativos",
    organizer: "Universidade Estadual do Rio Grande do Sul (Uergs)",
    description: "Competição nacional que desafia estudantes a propor e desenvolver aplicativos voltados a problemas reais e aos Objetivos de Desenvolvimento Sustentável.",
    type: "Olimpíada",
    areas: ["Tecnologia", "Programação", "Inovação", "Sustentabilidade", "Impacto social"],
    targetAudience: ["Ensino Médio"],
    participation: "Equipe",
    scope: "Nacional",
    format: "Híbrida",
    modalities: ["Aplicativos", "Tecnologia", "Projetos", "ODS"],
    minAge: null,
    maxAge: null,
    eligibility: "Historicamente voltada a equipes de estudantes do Ensino Médio com professor orientador. Consulte a organização para confirmar a próxima edição.",
    city: "Brasil",
    state: "",
    country: "Brasil",
    level: "Nacional",
    stages: ["Inscrição", "Projeto de aplicativo", "Desenvolvimento", "Vídeo/pitch", "Final"],
    registrationStart: null,
    registrationEnd: null,
    eventDate: null,
    officialUrl: "https://uergs.edu.br/mais-pela-extensao",
    regulationUrl: "https://uergs.edu.br/upload/arquivos/202204/08190055-edital-6a-onda.pdf",
    sourceName: "Uergs — ONDA",
    evidence: "A Uergs mantém a ONDA entre suas olimpíadas e documenta a competição nacional de aplicativos. Não foi localizada uma edição 2026 com calendário oficial publicado.",
    confidence: 80,
    status: "UNKNOWN",
    free: null,
    task: "Identificar um problema relevante, propor uma solução em aplicativo, desenvolver o projeto e apresentá-lo em formato de pitch.",
    prize: "Reconhecimento e premiações conforme o edital de cada edição.",
  }),
  item({
    id: "desafio-led-globo-2026",
    name: "Desafio LED Globo 2026 — Me Dá Uma Luz Aí!",
    organizer: "Globo / Fundação Roberto Marinho",
    description: "Desafio nacional de inovação em educação para estudantes criarem soluções para problemas reais do setor educacional.",
    type: "Desafio",
    areas: ["Educação", "Inovação", "Tecnologia", "Impacto social"],
    targetAudience: ["Ensino Superior"],
    participation: "Individual",
    scope: "Nacional",
    format: "Híbrida",
    modalities: ["Inovação", "Educação", "Projetos"],
    minAge: 18,
    maxAge: null,
    eligibility: "Estudantes maiores de 18 anos com matrícula ativa no primeiro semestre de 2026, conforme regras da edição.",
    city: "Rio de Janeiro",
    state: "RJ",
    country: "Brasil",
    level: "Nacional",
    stages: ["Inscrição", "Seleções", "Desenvolvimento", "Semifinal", "Final"],
    registrationStart: null,
    registrationEnd: "2026-03-08",
    eventDate: "2026-05-16",
    officialUrl: "https://somos.globo.com/movimento-led/desafio-led/",
    registrationUrl: "https://somos.globo.com/movimento-led/desafio-led/",
    sourceName: "Movimento LED Globo",
    evidence: "A edição 2026 recebeu inscrições até 08/03 e realizou a grande final no Festival LED em 16/05.",
    confidence: 100,
    status: "CLOSED",
    free: true,
    task: "Criar e desenvolver uma solução inovadora para o desafio educacional proposto na edição.",
    prize: "Premiação total de R$ 300 mil dividida entre cinco projetos vencedores na edição 2026.",
  }),
  item({
    id: "sapientia",
    name: "Sapientia — Olimpíada do Futuro",
    organizer: "Instituto Vertere",
    description: "Olimpíada voltada à criação de projetos reais para problemas contemporâneos, combinando provas individuais e desenvolvimento de soluções em equipe.",
    type: "Olimpíada",
    areas: ["Inovação", "Educação", "Empreendedorismo", "Impacto social", "ODS"],
    targetAudience: ["Ensino Fundamental", "Ensino Médio", "Ensino Superior"],
    participation: "Ambos",
    scope: "Nacional",
    format: "Híbrida",
    modalities: ["Conhecimento", "Projetos", "Inovação"],
    minAge: null,
    maxAge: null,
    eligibility: "Categoria principal: 8º e 9º anos do Ensino Fundamental, Ensino Médio, recém-formados no Ensino Médio e estudantes do 1º ano do Ensino Superior, conforme regras da organização.",
    city: "Brasil",
    state: "",
    country: "Brasil",
    level: "Nacional",
    stages: ["Prova objetiva", "Prova de soluções", "Pré-projeto", "Desenvolvimento em grupo", "Final presencial"],
    registrationStart: null,
    registrationEnd: null,
    eventDate: null,
    officialUrl: "https://olimpiadadofuturo.com.br/",
    registrationUrl: "https://olimpiadadofuturo.com.br/",
    regulationUrl: "https://olimpiadadofuturo.com.br/",
    sourceName: "Sapientia — Olimpíada do Futuro",
    evidence: "O site oficial apresenta a jornada em cinco fases e informa preparação para a próxima edição, sem calendário 2026 confirmado na página consultada.",
    confidence: 90,
    status: "UNKNOWN",
    free: null,
    task: "Resolver desafios sobre temas contemporâneos e transformar uma proposta em projeto aplicável à realidade local.",
    prize: "Reconhecimento e oportunidades definidos pelo regulamento de cada edição.",
  }),
  item({
    id: "mostratec-2026",
    name: "MOSTRATEC 2026 — Mostra Internacional de Ciência e Tecnologia",
    organizer: "Fundação Liberato",
    description: "Mostra internacional de ciência e tecnologia que reúne projetos de pesquisa e inovação de estudantes de diferentes níveis de ensino.",
    type: "Feira",
    areas: ["Ciência", "Tecnologia", "Engenharia", "Inovação", "Pesquisa"],
    targetAudience: ["Ensino Fundamental", "Ensino Médio", "Ensino Técnico", "Ensino Superior"],
    participation: "Equipe",
    scope: "Internacional",
    format: "Presencial",
    modalities: ["Pesquisa", "Ciência", "Tecnologia", "Engenharia", "Projetos"],
    minAge: null,
    maxAge: null,
    eligibility: "Projetos selecionados pelo processo de seleção da MOSTRATEC ou credenciados por feiras afiliadas, conforme regulamento e prazos aplicáveis.",
    city: "Novo Hamburgo",
    state: "RS",
    country: "Brasil",
    level: "Internacional",
    stages: ["Submissão", "Seleção/credenciamento", "Final presencial", "Premiação"],
    registrationStart: "2026-07-01",
    registrationEnd: "2026-09-30",
    eventDate: "2026-10-26",
    officialUrl: "https://mostratec.liberato.com.br/",
    registrationUrl: "https://mostratec.liberato.com.br/cronograma/",
    regulationUrl: "https://mostratec.liberato.com.br/cronograma/",
    sourceName: "MOSTRATEC — Fundação Liberato",
    evidence: "O calendário 2026 prevê a MOSTRATEC de 26 a 30/10 e mantém inscrições de projetos credenciados por feiras afiliadas até 30/09, conforme a data da feira de origem.",
    confidence: 100,
    status: "OPEN",
    free: null,
    task: "Submeter e apresentar um projeto de pesquisa, ciência, tecnologia ou inovação.",
    prize: "Premiações, certificados e credenciamentos para feiras e oportunidades científicas conforme categoria.",
  }),
  item({
    id: "obt-2026",
    name: "5ª Olimpíada Brasileira de Tecnologia (OBT) 2026",
    organizer: "Instituto Alpha Lumen / MIT Brazil",
    description: "Olimpíada nacional de tecnologia que trabalha matemática aplicada, lógica computacional, ODS, prototipagem e desenvolvimento de soluções digitais.",
    type: "Olimpíada",
    areas: ["Tecnologia", "Programação", "Computação", "Inovação", "ODS"],
    targetAudience: ["Ensino Fundamental", "Ensino Médio"],
    participation: "Equipe",
    scope: "Nacional",
    format: "Híbrida",
    modalities: ["Tecnologia", "Lógica", "Prototipagem", "Aplicativos"],
    minAge: null,
    maxAge: null,
    eligibility: "Estudantes do 8º e 9º anos do Ensino Fundamental e do Ensino Médio de escolas públicas ou privadas, conforme regulamento da 5ª edição.",
    city: "São José dos Campos",
    state: "SP",
    country: "Brasil",
    level: "Nacional",
    stages: ["Desafios de lógica e matemática", "Prototipagem", "Desafio App / Escola Avançada de Tecnologia"],
    registrationStart: null,
    registrationEnd: null,
    eventDate: "2026-07-28",
    officialUrl: "https://www.alphalumen.org.br/olimpiada-brasileira-de-tecnologia-obt/",
    registrationUrl: "https://www.alphalumen.org.br/olimpiada-brasileira-de-tecnologia-obt/",
    regulationUrl: "https://www.alphalumen.org.br/olimpiada-brasileira-de-tecnologia-obt/",
    sourceName: "Instituto Alpha Lumen — OBT",
    evidence: "A 5ª edição ocorreu em 2026 e culminou na Escola Avançada de Tecnologia, com premiação e Mostra do Desafio App no fim de julho.",
    confidence: 95,
    status: "CLOSED",
    free: true,
    task: "Resolver desafios de lógica e matemática aplicada, investigar problemas ligados aos ODS e prototipar/desenvolver uma solução tecnológica.",
    prize: "Medalhas e oportunidades de formação e imersão ligadas ao ecossistema Alpha Lumen/MIT Brazil, conforme classificação.",
  }),
  item({
    id: "oba-2026",
    name: "29ª Olimpíada Brasileira de Astronomia e Astronáutica (OBA) 2026",
    organizer: "Sociedade Astronômica Brasileira (SAB)",
    description: "Olimpíada nacional de astronomia e astronáutica para estudantes da educação básica de escolas públicas e privadas.",
    type: "Olimpíada",
    areas: ["Astronomia", "Astronáutica", "Física", "Ciência"],
    targetAudience: ["Ensino Fundamental", "Ensino Médio"],
    participation: "Individual",
    scope: "Nacional",
    format: "Presencial",
    modalities: ["Astronomia", "Astronáutica"],
    minAge: null,
    maxAge: null,
    eligibility: "Estudantes de escolas públicas ou privadas participantes da OBA, conforme níveis e regras oficiais.",
    city: "Brasil",
    state: "",
    country: "Brasil",
    level: "Nacional",
    stages: ["Inscrição", "Prova da OBA", "Premiação", "Seletivas internacionais para classificados"],
    registrationStart: "2026-02-23",
    registrationEnd: "2026-05-01",
    eventDate: null,
    officialUrl: "https://www.oba.org.br/",
    registrationUrl: "https://app.oba.org.br/",
    regulationUrl: "https://www.oba.org.br/",
    sourceName: "OBA — Sociedade Astronômica Brasileira",
    evidence: "O calendário oficial de 2026 informa inscrições de estudantes de 23/02 a 01/05 para a 29ª OBA.",
    confidence: 100,
    status: "CLOSED",
    free: null,
    task: "Realizar prova de conhecimentos em astronomia e astronáutica de acordo com o nível escolar.",
    prize: "Medalhas, certificados e possibilidade de participação em seletivas para olimpíadas internacionais.",
  }),
  item({
    id: "solve-for-tomorrow-brasil-2026",
    name: "Solve for Tomorrow Brasil 2026",
    organizer: "Samsung / Cenpec",
    description: "Programa de inovação que desafia estudantes do Ensino Médio da rede pública a desenvolver soluções para problemas reais de suas comunidades usando abordagem STEM.",
    type: "Desafio",
    areas: ["Ciência", "Tecnologia", "Engenharia", "Matemática", "Inovação", "Impacto social"],
    targetAudience: ["Ensino Médio"],
    participation: "Equipe",
    scope: "Nacional",
    format: "Híbrida",
    modalities: ["STEM", "Projetos", "Inovação", "Impacto social"],
    minAge: null,
    maxAge: null,
    eligibility: "Equipes de estudantes do Ensino Médio de escolas públicas, inscritas por professor(a), conforme regras da 13ª edição.",
    city: "Brasil",
    state: "",
    country: "Brasil",
    level: "Nacional",
    stages: ["Inscrição", "Seleção", "Semifinal", "Mentorias", "Final e premiação"],
    registrationStart: "2026-04-23",
    registrationEnd: "2026-07-13",
    eventDate: null,
    officialUrl: "https://solvefortomorrowbrasil.com.br/",
    registrationUrl: "https://solvefortomorrowbrasil.com.br/",
    regulationUrl: "https://solvefortomorrowbrasil.com.br/",
    sourceName: "Samsung Solve for Tomorrow Brasil",
    evidence: "A 13ª edição teve inscrições prorrogadas até 13/07/2026 e já está na fase de semifinalistas e mentorias.",
    confidence: 100,
    status: "CLOSED",
    free: true,
    task: "Desenvolver em equipe uma solução inovadora para um desafio real da comunidade usando conhecimentos de ciência, tecnologia, engenharia e matemática.",
    prize: "Reconhecimento nacional, mentorias, troféus e premiações para projetos vencedores conforme categorias da edição 2026.",
  }),

];

export const COMPETITION_SEARCH_TAXONOMY = [
  "Robótica","Ciência","Tecnologia","Inovação","Programação","Inteligência Artificial",
  "Empreendedorismo","Sustentabilidade","Meio ambiente","Engenharia","Eletrônica","Games",
  "Hackathon","Pesquisa","Projetos","Startup","Educação","Matemática","Física","Química",
  "Biologia","Astronomia","Design","Criatividade","Saúde","Biotecnologia","Dados",
  "Segurança cibernética","Energia","Cidades inteligentes","Impacto social",
] as const;
