import AdminShell from "@/components/admin/AdminShell";
import styles from "@/components/admin/AdminViews.module.css";
import { updatePrivacyRequestAdminAction } from "@/lib/admin/actions";
import { requireAdminUser } from "@/lib/admin/require-admin";

export default async function AdminPrivacy({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const query=await searchParams;const {supabase,profile}=await requireAdminUser();
 const {data:requests}=await supabase.from("privacy_requests").select("id,user_id,request_type,details,status,admin_note,requested_at,resolved_at").order("requested_at",{ascending:true}).limit(200);
 const ids=Array.from(new Set((requests??[]).map((item:any)=>item.user_id)));let profiles:any[]=[];if(ids.length){const result=await supabase.from("profiles").select("id,username,display_name").in("id",ids);profiles=result.data??[];}const profileMap=new Map(profiles.map((p:any)=>[p.id,p]));
 return <AdminShell profile={profile} title="Privacidade"><div className={styles.head}><div><h1>Solicitações de privacidade</h1><p className={styles.muted}>Acesso, correção, exportação, exclusão e outros pedidos registrados pelos titulares.</p></div></div>{query.status?<div className={styles.notice}>Solicitação atualizada e registrada no log.</div>:null}{query.error?<div className={styles.error}>Não foi possível atualizar a solicitação.</div>:null}<div className={styles.warning}>Marcar um pedido como concluído não apaga magicamente uma conta do Supabase Auth. Exclusão deve ser executada por fluxo privilegiado e verificada antes de encerrar o pedido.</div><div className={styles.stack}>{(requests??[]).length===0?<div className={styles.empty}>Nenhuma solicitação.</div>:(requests??[]).map((request:any)=>{const user=profileMap.get(request.user_id);return <article className={styles.request} key={request.id}><div className={styles.actions}><span className={styles.pill}>{request.request_type}</span><span className={styles.pill}>{request.status}</span></div><h3>{user?.display_name??"Conta"}</h3><p className={styles.muted}>{user?.username?`@${user.username}`:""} · {new Date(request.requested_at).toLocaleString("pt-BR")}</p><p>{request.details||"Sem detalhes adicionais."}</p><form className={styles.form} action={updatePrivacyRequestAdminAction}><input type="hidden" name="request_id" value={request.id}/><label>Status<select name="status" defaultValue={request.status}><option value="open">Aberta</option><option value="in_review">Em análise</option><option value="completed">Concluída</option><option value="rejected">Rejeitada</option></select></label><label>Nota administrativa<textarea name="admin_note" defaultValue={request.admin_note} maxLength={2000}/></label><button className={styles.primary}>Salvar atendimento</button></form></article>;})}</div></AdminShell>;
}
