import AdminShell from "@/components/admin/AdminShell";
import styles from "@/components/admin/AdminViews.module.css";
import { updateMessageReportAdminAction } from "@/lib/admin/actions";
import { requireAdminUser } from "@/lib/admin/require-admin";

export default async function AdminModeration({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const query=await searchParams;const {supabase,profile}=await requireAdminUser();
 const {data:reports}=await supabase.from("message_reports").select("id,reporter_id,message_id,reason,details,status,admin_note,created_at,resolved_at").order("created_at",{ascending:false}).limit(200);
 const messageIds=(reports??[]).map((r:any)=>r.message_id);let messages:any[]=[];
 if(messageIds.length){const result=await supabase.from("direct_messages").select("id,sender_id,body,created_at").in("id",messageIds);messages=result.data??[];}
 const profileIds=Array.from(new Set([...(reports??[]).map((r:any)=>r.reporter_id),...messages.map((m:any)=>m.sender_id)]));let profiles:any[]=[];
 if(profileIds.length){const result=await supabase.from("profiles").select("id,username,display_name").in("id",profileIds);profiles=result.data??[];}
 const messageMap=new Map(messages.map((m:any)=>[m.id,m]));const profileMap=new Map(profiles.map((p:any)=>[p.id,p]));
 return <AdminShell profile={profile} title="Moderação"><div className={styles.head}><div><h1>Denúncias de mensagens</h1><p className={styles.muted}>O admin recebe acesso apenas às mensagens efetivamente denunciadas, não ao histórico geral de conversas.</p></div></div>{query.status?<div className={styles.notice}>Denúncia atualizada e ação registrada no log.</div>:null}{query.error?<div className={styles.error}>Não foi possível atualizar a denúncia.</div>:null}<div className={styles.stack}>{(reports??[]).length===0?<div className={styles.empty}>Nenhuma denúncia registrada.</div>:(reports??[]).map((report:any)=>{const message=messageMap.get(report.message_id);const reporter=profileMap.get(report.reporter_id);const sender=message?profileMap.get(message.sender_id):null;return <article className={styles.request} key={report.id}><div className={styles.actions}><span className={styles.pill}>{report.status}</span><span className={styles.pill}>{report.reason}</span></div><h3>Mensagem denunciada</h3><p>{message?.body??"Mensagem indisponível."}</p><p className={styles.muted}>Autor: {sender?.display_name??"Conta"} {sender?.username?`(@${sender.username})`:""} · Denunciante: {reporter?.display_name??"Conta"}</p>{report.details?<p><strong>Detalhes:</strong> {report.details}</p>:null}<form className={styles.form} action={updateMessageReportAdminAction}><input type="hidden" name="report_id" value={report.id}/><label>Status<select name="status" defaultValue={report.status}><option value="open">Aberta</option><option value="reviewing">Em análise</option><option value="resolved">Resolvida</option><option value="dismissed">Descartada</option></select></label><label>Nota administrativa<textarea name="admin_note" defaultValue={report.admin_note} maxLength={2000}/></label><button className={styles.primary}>Salvar análise</button></form></article>;})}</div></AdminShell>;
}
