import Link from "next/link";
import AdminShell from "@/components/admin/AdminShell";
import AdminPagination from "@/components/admin/AdminPagination";
import styles from "@/components/admin/AdminViews.module.css";
import { createCourseAdminAction } from "@/lib/admin/actions";
import { requireAdminUser } from "@/lib/admin/require-admin";

const PAGE_SIZE=20;
function pageNumber(value:string|string[]|undefined){const raw=typeof value==="string"?Number.parseInt(value,10):1;return Number.isFinite(raw)&&raw>0?raw:1;}

export default async function AdminCourses({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const {supabase,profile}=await requireAdminUser();const params=await searchParams;const page=pageNumber(params.page);const from=(page-1)*PAGE_SIZE;
 const {data:courses,count,error}=await supabase.from("courses").select("id,slug,title,level,status,duration_minutes,updated_at",{count:"exact"}).order("updated_at",{ascending:false}).range(from,from+PAGE_SIZE-1);
 return <AdminShell profile={profile} title="Cursos"><div className={styles.head}><div><h1>Cursos</h1><p className={styles.muted}>Conteúdo educacional administrado no banco. Competições ficam fora deste módulo.</p></div></div>{params.error?<div className={styles.error}>Não foi possível concluir a operação.</div>:null}{error?<div className={styles.error}>Não foi possível carregar os cursos.</div>:null}<div className={styles.grid}><section className={styles.card}><h2>Novo curso</h2><form className={styles.form} action={createCourseAdminAction}><label>Título<input name="title" maxLength={160} required/></label><label>Slug opcional<input name="slug" maxLength={120} placeholder="gerado pelo título"/></label><label>Descrição<textarea name="description" maxLength={3000}/></label><label>Instrutor<input name="instructor" maxLength={160} defaultValue="Equipe Envista"/></label><label>Nível<input name="level" maxLength={80} defaultValue="Iniciante"/></label><label>Duração em minutos<input name="duration_minutes" type="number" min="0" max="100000" defaultValue="0"/></label><label>Status<select name="status" defaultValue="draft"><option value="draft">Rascunho</option><option value="published">Publicado</option><option value="archived">Arquivado</option></select></label><button className={styles.primary}>Criar curso</button></form></section><section className={styles.card}><h2>Cursos cadastrados</h2><div className={styles.stack}>{!error&&(courses??[]).length===0?<div className={styles.empty}>Nenhum curso.</div>:(courses??[]).map((course:any)=><Link href={`/admin/courses/${course.id}`} key={course.id} className={styles.request} style={{textDecoration:"none",color:"inherit"}}><h3>{course.title}</h3><div className={styles.actions}><span className={styles.pill}>{course.status}</span><span className={styles.pill}>{course.level}</span><span className={styles.pill}>{course.duration_minutes} min</span></div><small className={styles.muted}>/{course.slug}</small></Link>)}</div>{!error?<AdminPagination pathname="/admin/courses" page={page} pageSize={PAGE_SIZE} total={count??0}/>:null}</section></div></AdminShell>;
}
