import Link from "next/link";
import FollowEntityButton from "@/components/real/FollowEntityButton";
import { addPostCommentAction, createPostAction, deletePostAction, deletePostCommentAction, togglePostLikeAction } from "@/lib/social-real/actions";
import styles from "./Social.module.css";

type Role="participant"|"investor";
type TeamOption={id:string;name:string};
type CommentView={id:string;body:string;user_id:string;parentCommentId:string|null;authorLabel:string;authorHref:string};
type PostView={id:string;body:string;visibility:string;created_at:string;authorLabel:string;authorHref:string;canDelete:boolean;liked:boolean;likeCount:number;comments:CommentView[]};
function base(role:Role){return role==="investor"?"/investor":"/app";}
function time(value:string){try{return new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(value));}catch{return value;}}

function Comment({comment,replies,userId,path,postId}:{comment:CommentView;replies:CommentView[];userId:string;path:string;postId:string}){
 return <div className={styles.commentThread}>
  <div className={styles.commentRow}>
   <div className={styles.commentMeta}><Link href={comment.authorHref}>{comment.authorLabel}</Link></div>
   <p>{comment.body}</p>
   <div className={styles.commentActions}>
    <details className={styles.replyBox}><summary>Responder</summary><form className={styles.comment} action={addPostCommentAction}><input type="hidden" name="post_id" value={postId}/><input type="hidden" name="parent_comment_id" value={comment.id}/><input type="hidden" name="return_to" value={path}/><input required name="body" maxLength={2000} placeholder={`Responder a ${comment.authorLabel}…`}/><button className={styles.primary}>Responder</button></form></details>
    {comment.user_id===userId&&<form action={deletePostCommentAction}><input type="hidden" name="comment_id" value={comment.id}/><input type="hidden" name="return_to" value={path}/><button className={styles.danger}>Excluir</button></form>}
   </div>
  </div>
  {replies.length?<div className={styles.replyList}>{replies.map(reply=><div className={styles.reply} key={reply.id}><div className={styles.commentMeta}><Link href={reply.authorHref}>{reply.authorLabel}</Link><span>respondeu a {comment.authorLabel}</span></div><p>{reply.body}</p>{reply.user_id===userId&&<form action={deletePostCommentAction}><input type="hidden" name="comment_id" value={reply.id}/><input type="hidden" name="return_to" value={path}/><button className={styles.danger}>Excluir</button></form>}</div>)}</div>:null}
 </div>;
}

export function SocialFeedView({role,userId,teams,posts,status,error}:{role:Role;userId:string;teams:TeamOption[];posts:PostView[];status?:string;error?:string}){
 const path=`${base(role)}/social`;
 const errorMessage=error==="profile-private"?"Seu perfil está privado. Torne-o visível na plataforma para publicar para todos.":error==="team-private"?"Essa equipe está privada e não pode publicar para toda a plataforma.":error==="reply-depth"?"As respostas podem ter apenas um nível por enquanto.":error?"Não foi possível concluir a ação.":"";
 return <><div className={styles.head}><div><h1>Social</h1><p className={styles.muted}>Publicações, comentários e conversas entre pessoas e equipes do Envista.</p></div><Link className={styles.secondary} href={`${base(role)}/explore`}>Explorar</Link></div>{status==="posted"&&<div className={styles.notice}>Publicação criada.</div>}{errorMessage&&<div className={styles.error}>{errorMessage}</div>}
 <div className={styles.layout}><div className={styles.stack}><section className={styles.card}><form className={styles.composer} action={createPostAction}><input type="hidden" name="return_to" value={path}/><label>Publicar como<select name="author" defaultValue="personal"><option value="personal">Meu perfil</option>{teams.map(team=><option key={team.id} value={team.id}>Equipe · {team.name}</option>)}</select></label><textarea required maxLength={5000} name="body" placeholder="Compartilhe um avanço, aprendizado ou atualização…"/><label>Visibilidade<select name="visibility" defaultValue="platform"><option value="platform">Na plataforma</option><option value="private">Privado para mim/minha equipe</option></select></label><button className={styles.primary}>Publicar</button></form></section>
 {posts.length===0?<div className={styles.empty}>Ainda não há publicações visíveis.</div>:posts.map(post=>{const roots=post.comments.filter(comment=>!comment.parentCommentId);return <article className={styles.card} key={post.id}><div className={styles.author}><div><Link href={post.authorHref}>{post.authorLabel}</Link><small>{time(post.created_at)} · {post.visibility==="private"?"Privado":"Plataforma"}</small></div>{post.canDelete&&<form action={deletePostAction}><input type="hidden" name="post_id" value={post.id}/><input type="hidden" name="return_to" value={path}/><button className={styles.danger}>Excluir</button></form>}</div><p className={styles.body}>{post.body}</p><div className={styles.actions}><form action={togglePostLikeAction}><input type="hidden" name="post_id" value={post.id}/><input type="hidden" name="return_to" value={path}/><button className={styles.secondary}>{post.liked?"♥ Curtido":"♡ Curtir"}</button></form><span className={styles.counts}>{post.likeCount} curtida{post.likeCount===1?"":"s"} · {post.comments.length} comentário{post.comments.length===1?"":"s"}</span></div><div className={styles.comments}>{roots.map(comment=><Comment key={comment.id} comment={comment} replies={post.comments.filter(reply=>reply.parentCommentId===comment.id)} userId={userId} path={path} postId={post.id}/>) }<form className={styles.comment} action={addPostCommentAction}><input type="hidden" name="post_id" value={post.id}/><input type="hidden" name="return_to" value={path}/><input required name="body" maxLength={2000} placeholder="Comentar…"/><button className={styles.primary}>Enviar</button></form></div></article>})}</div>
 <aside className={styles.stack}><section className={styles.card}><h3>Interações do Envista</h3><p className={styles.muted}>Posts, curtidas, comentários, respostas e follows ficam vinculados à sua conta e protegidos pelas regras de acesso da plataforma.</p></section></aside></div></>;
}

type ExploreProfile={id:string;username:string;display_name:string;bio:string|null;role:string};
type ExploreTeam={id:string;slug:string;name:string;description:string;category:string};
type ExploreProject={id:string;slug:string;title:string;short_description:string;stage:string};
export function ExploreView({role,profiles,teams,projects}:{role:Role;profiles:ExploreProfile[];teams:ExploreTeam[];projects:ExploreProject[]}){
 const root=base(role);return <><div className={styles.head}><div><h1>Explorar</h1><p className={styles.muted}>Descubra pessoas, equipes e projetos publicados na plataforma.</p></div></div>
 <section><h2>Pessoas</h2>{profiles.length===0?<div className={styles.empty}>Nenhum perfil público ainda.</div>:<div className={styles.entityGrid}>{profiles.map(p=><article className={styles.entity} key={p.id}><Link className={styles.entityMainLink} href={`${root}/${p.role==="investor"?"investors":"participants"}/${p.username}`}><h3>{p.display_name}</h3><p className={styles.muted}>@{p.username}</p><p>{p.bio||"Sem bio."}</p></Link><div className={styles.entityAction}><FollowEntityButton targetType="profile" targetId={p.id} returnTo={`${root}/explore`}/></div></article>)}</div>}</section>
 <section><h2>Equipes</h2>{teams.length===0?<div className={styles.empty}>Nenhuma equipe publicada ainda.</div>:<div className={styles.entityGrid}>{teams.map(t=><article className={styles.entity} key={t.id}><Link className={styles.entityMainLink} href={`${root}/teams/${t.slug}`}><h3>{t.name}</h3><p>{t.description||"Sem descrição."}</p></Link><div className={styles.entityAction}><FollowEntityButton targetType="team" targetId={t.id} returnTo={`${root}/explore`}/></div></article>)}</div>}</section>
 <section><h2>Projetos</h2>{projects.length===0?<div className={styles.empty}>Nenhum projeto publicado ainda.</div>:<div className={styles.entityGrid}>{projects.map(p=><article className={styles.entity} key={p.id}><Link className={styles.entityMainLink} href={`${root}/projects/${p.slug}`}><h3>{p.title}</h3><p>{p.short_description||"Sem descrição."}</p><span className={styles.pill}>{p.stage}</span></Link><div className={styles.entityAction}><FollowEntityButton targetType="project" targetId={p.id} returnTo={`${root}/explore`}/></div></article>)}</div>}</section></>;
}

export function PublicProfileView({role,profile,posts}:{role:Role;profile:ExploreProfile & {public_city?:string|null;public_state?:string|null;public_school?:string|null;organization?:string|null;organization_type?:string|null};posts:{id:string;body:string;created_at:string}[]}){
 const root=base(role);const returnTo=`${root}/${profile.role==="investor"?"investors":"participants"}/${profile.username}`;
 return <><div className={styles.head}><div><h1>{profile.display_name}</h1><p className={styles.muted}>@{profile.username} · {profile.role==="investor"?"Investidor":"Participante"}</p></div><div className={styles.actions}><FollowEntityButton targetType="profile" targetId={profile.id} returnTo={returnTo}/><Link className={styles.secondary} href={`${root}/messages?to=${profile.id}`}>Mensagem</Link></div></div><div className={styles.layout}><div className={styles.stack}><section className={styles.card}><h2>{profile.role==="participant"?"Escolas":"Organização"}</h2>{profile.role==="participant"?<p>{profile.public_school||"Nenhuma escola ou instituição informada."}</p>:<p>{profile.organization||"Nenhuma organização informada."}</p>}{profile.public_city&&<p><strong>Local:</strong> {profile.public_city}{profile.public_state?` · ${profile.public_state}`:""}</p>}</section><section className={styles.card}><h2>Apresentação</h2><p>{profile.bio||"Sem apresentação."}</p></section><section className={styles.stack}><h2>Publicações</h2>{posts.length===0?<div className={styles.empty}>Nenhuma publicação pública.</div>:posts.map(post=><article className={styles.card} key={post.id}><p className={styles.body}>{post.body}</p><small className={styles.muted}>{time(post.created_at)}</small></article>)}</section></div></div></>;
}
