import Link from "next/link";
import FollowEntityButton from "@/components/real/FollowEntityButton";
import { addPostCommentAction, createPostAction, deletePostAction, deletePostCommentAction, togglePostLikeAction } from "@/lib/social-real/actions";
import styles from "./Social.module.css";

type Role="participant"|"investor";
type TeamOption={id:string;name:string};
type CommentView={id:string;body:string;user_id:string;authorLabel:string};
type PostView={id:string;body:string;visibility:string;created_at:string;authorLabel:string;authorHref:string;canDelete:boolean;liked:boolean;likeCount:number;comments:CommentView[]};
function base(role:Role){return role==="investor"?"/investor":"/app";}
function time(value:string){try{return new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(value));}catch{return value;}}

export function SocialFeedView({role,userId,teams,posts,status,error}:{role:Role;userId:string;teams:TeamOption[];posts:PostView[];status?:string;error?:string}){
 const path=`${base(role)}/social`;
 return <><div className={styles.head}><div><h1>Social</h1><p className={styles.muted}>Publicações reais de pessoas e equipes do Envista.</p></div><Link className={styles.secondary} href={`${base(role)}/explore`}>Explorar</Link></div>{status==="posted"&&<div className={styles.notice}>Publicação criada.</div>}{error&&<div className={styles.error}>Não foi possível concluir a ação.</div>}
 <div className={styles.layout}><div className={styles.stack}><section className={styles.card}><form className={styles.composer} action={createPostAction}><input type="hidden" name="return_to" value={path}/><label>Publicar como<select name="author" defaultValue="personal"><option value="personal">Meu perfil</option>{teams.map(team=><option key={team.id} value={team.id}>Equipe · {team.name}</option>)}</select></label><textarea required maxLength={5000} name="body" placeholder="Compartilhe um avanço, aprendizado ou atualização…"/><label>Visibilidade<select name="visibility" defaultValue="platform"><option value="platform">Na plataforma</option><option value="private">Privado para mim/minha equipe</option></select></label><button className={styles.primary}>Publicar</button></form></section>
 {posts.length===0?<div className={styles.empty}>Ainda não há publicações visíveis.</div>:posts.map(post=><article className={styles.card} key={post.id}><div className={styles.author}><div><Link href={post.authorHref}>{post.authorLabel}</Link><small>{time(post.created_at)} · {post.visibility==="private"?"Privado":"Plataforma"}</small></div>{post.canDelete&&<form action={deletePostAction}><input type="hidden" name="post_id" value={post.id}/><input type="hidden" name="return_to" value={path}/><button className={styles.danger}>Excluir</button></form>}</div><p className={styles.body}>{post.body}</p><div className={styles.actions}><form action={togglePostLikeAction}><input type="hidden" name="post_id" value={post.id}/><input type="hidden" name="return_to" value={path}/><button className={styles.secondary}>{post.liked?"♥ Curtido":"♡ Curtir"}</button></form><span className={styles.counts}>{post.likeCount} curtida{post.likeCount===1?"":"s"} · {post.comments.length} comentário{post.comments.length===1?"":"s"}</span></div><div className={styles.comments}>{post.comments.map(comment=><div className={styles.commentRow} key={comment.id}><strong>{comment.authorLabel}</strong><p>{comment.body}</p>{comment.user_id===userId&&<form action={deletePostCommentAction}><input type="hidden" name="comment_id" value={comment.id}/><input type="hidden" name="return_to" value={path}/><button className={styles.danger}>Excluir comentário</button></form>}</div>)}<form className={styles.comment} action={addPostCommentAction}><input type="hidden" name="post_id" value={post.id}/><input type="hidden" name="return_to" value={path}/><input required name="body" maxLength={2000} placeholder="Comentar…"/><button className={styles.primary}>Enviar</button></form></div></article>)}</div>
 <aside className={styles.stack}><section className={styles.card}><h3>Seu social agora é real</h3><p className={styles.muted}>Posts, likes, comentários e follows ficam vinculados à sua conta e protegidos por RLS.</p></section></aside></div></>;
}

type ExploreProfile={id:string;username:string;display_name:string;bio:string|null;role:string};
type ExploreTeam={id:string;slug:string;name:string;description:string;category:string};
type ExploreProject={id:string;slug:string;title:string;short_description:string;stage:string};
export function ExploreView({role,profiles,teams,projects}:{role:Role;profiles:ExploreProfile[];teams:ExploreTeam[];projects:ExploreProject[]}){
 const root=base(role);return <><div className={styles.head}><div><h1>Explorar</h1><p className={styles.muted}>Descubra dados publicados de verdade na plataforma.</p></div></div>
 <section><h2>Pessoas</h2>{profiles.length===0?<div className={styles.empty}>Nenhum perfil público ainda.</div>:<div className={styles.entityGrid}>{profiles.map(p=><article className={styles.entity} key={p.id}><Link href={`${root}/${p.role==="investor"?"investors":"participants"}/${p.username}`}><h3>{p.display_name}</h3><p className={styles.muted}>@{p.username}</p></Link><p>{p.bio||"Sem bio."}</p><FollowEntityButton targetType="profile" targetId={p.id} returnTo={`${root}/explore`}/></article>)}</div>}</section>
 <section><h2>Equipes</h2>{teams.length===0?<div className={styles.empty}>Nenhuma equipe publicada ainda.</div>:<div className={styles.entityGrid}>{teams.map(t=><article className={styles.entity} key={t.id}><Link href={`${root}/teams/${t.slug}`}><h3>{t.name}</h3><p>{t.description||"Sem descrição."}</p></Link><FollowEntityButton targetType="team" targetId={t.id} returnTo={`${root}/explore`}/></article>)}</div>}</section>
 <section><h2>Projetos</h2>{projects.length===0?<div className={styles.empty}>Nenhum projeto publicado ainda.</div>:<div className={styles.entityGrid}>{projects.map(p=><article className={styles.entity} key={p.id}><Link href={`${root}/projects/${p.slug}`}><h3>{p.title}</h3><p>{p.short_description||"Sem descrição."}</p><span className={styles.pill}>{p.stage}</span></Link><FollowEntityButton targetType="project" targetId={p.id} returnTo={`${root}/explore`}/></article>)}</div>}</section></>;
}

export function PublicProfileView({role,profile,posts}:{role:Role;profile:ExploreProfile & {public_city?:string|null;public_state?:string|null;public_school?:string|null;organization?:string|null;organization_type?:string|null};posts:{id:string;body:string;created_at:string}[]}){
 const root=base(role);const returnTo=`${root}/${profile.role==="investor"?"investors":"participants"}/${profile.username}`;
 return <><div className={styles.head}><div><h1>{profile.display_name}</h1><p className={styles.muted}>@{profile.username} · {profile.role==="investor"?"Investidor":"Participante"}</p></div><div className={styles.actions}><FollowEntityButton targetType="profile" targetId={profile.id} returnTo={returnTo}/><Link className={styles.secondary} href={`${root}/messages?to=${profile.id}`}>Mensagem</Link></div></div><div className={styles.layout}><div className={styles.stack}><section className={styles.card}><h2>Sobre</h2><p>{profile.bio||"Sem bio."}</p>{profile.public_school&&<p><strong>Instituição:</strong> {profile.public_school}</p>}{profile.organization&&<p><strong>Organização:</strong> {profile.organization}</p>}{profile.public_city&&<p><strong>Local:</strong> {profile.public_city}{profile.public_state?` · ${profile.public_state}`:""}</p>}</section><section className={styles.stack}><h2>Publicações</h2>{posts.length===0?<div className={styles.empty}>Nenhuma publicação pública.</div>:posts.map(post=><article className={styles.card} key={post.id}><p className={styles.body}>{post.body}</p><small className={styles.muted}>{time(post.created_at)}</small></article>)}</section></div></div></>;
}
