import Link from "next/link";
import { CheckCircle2, ExternalLink, GitBranch, Circle } from "lucide-react";
import ContentTabs from "@/components/ui/ContentTabs";
import ProjectCover from "./ProjectCover";
import { loadProjectMedia } from "@/lib/projects/media";
import { requireProductUser, type ProductRole } from "@/lib/auth/require-product-user";
import styles from "./ProjectStory.module.css";

type StoryProject = { id: string; slug: string; title: string; category?: string; problem?: string; solution?: string; readme?: string; tags?: string[]; owner_team_id?: string | null; repository_url?: string | null; demo_url?: string | null; design_url?: string | null; updated_at?: string };

export default async function ProjectStory({ project, role, owner, canEdit }: { project: StoryProject; role: ProductRole; owner: string; canEdit: boolean }) {
  const { supabase } = await requireProductUser(role);
  const empty = Promise.resolve({ data: [], error: null });
  const repository = project.repository_url?.replace(/\.git$/, "").replace(/\/$/, "");
  const [media, milestones, updates, members, posts, github] = await Promise.all([
    loadProjectMedia(supabase, [project.id]),
    supabase.from("project_milestones").select("id,title,description,due_date,completed_at").eq("project_id", project.id).order("position").limit(30),
    supabase.from("project_updates").select("id,title,body,created_at").eq("project_id", project.id).order("created_at", { ascending: false }).limit(30),
    project.owner_team_id ? supabase.from("team_members").select("user_id,role_label,profiles:user_id(display_name,username)").eq("team_id", project.owner_team_id).limit(30) : empty,
    supabase.from("posts").select("id,body,created_at").eq("project_id", project.id).eq("visibility", "platform").order("created_at", { ascending: false }).limit(20),
    repository ? supabase.from("github_events").select("id,title,summary,event_html_url,occurred_at").eq("repository_html_url", repository).eq("is_public", true).order("occurred_at", { ascending: false }).limit(20) : empty,
  ]);
  const images = media.get(project.id) ?? [];
  const next = milestones.data?.find(item => !item.completed_at);
  const links = [[project.demo_url, "Ver demonstração"], [project.repository_url, "Abrir repositório"], [project.design_url, "Design e protótipo"]].filter((entry): entry is [string, string] => Boolean(entry[0]));
  const overview = <div className={styles.overview}><div className={styles.prose}><h2>Problema</h2><p>{project.problem || "O problema que este projeto resolve ainda não foi descrito."}</p><h2>Solução</h2><p>{project.solution || "A solução está sendo construída."}</p>{project.readme ? <><h2>Sobre o projeto</h2><p>{project.readme}</p></> : null}{images.length ? <><h2>Galeria</h2><div className={styles.gallery}>{images.map(image => <a key={image.url} href={image.url} target="_blank" rel="noreferrer"><ProjectCover title={project.title} src={image.url} /><span>{image.name}</span></a>)}</div></> : <p className={styles.muted}>Adicione screenshots ou fotos em Arquivos para apresentar o projeto visualmente.</p>}</div><aside className={styles.aside}><h3>Construído por</h3><p>{owner}</p><h3>Tecnologias e áreas</h3><div className={styles.skills}>{(project.tags ?? []).map(tag => <span key={tag}>{tag}</span>)}</div><h3>Próximo objetivo</h3><p>{next?.title || "A equipe ainda não definiu o próximo marco."}</p>{next?.due_date ? <small>Até {new Date(`${next.due_date}T12:00:00`).toLocaleDateString("pt-BR")}</small> : null}{canEdit ? <Link className="secondary" href={`/app/projects/${encodeURIComponent(project.slug)}/cockpit`}>Gerenciar evolução</Link> : null}{project.updated_at ? <small>Atualizado em {new Date(project.updated_at).toLocaleDateString("pt-BR")}</small> : null}</aside></div>;
  const evolution = <div className={styles.prose}><h2>Evolução do projeto</h2>{updates.error || milestones.error ? <p role="alert">Não foi possível carregar toda a evolução. Recarregue a página.</p> : null}{updates.data?.length ? <ol className={styles.timeline}>{updates.data.map(update => <li key={update.id}><time>{new Date(update.created_at).toLocaleDateString("pt-BR")}</time><div><h3>{update.title}</h3><p>{update.body}</p></div></li>)}</ol> : <p>Ainda não há atualizações registradas.</p>}<h2>Marcos</h2>{milestones.data?.length ? milestones.data.map(item => <div className={styles.milestone} key={item.id}>{item.completed_at ? <CheckCircle2 size={18} /> : <Circle size={18} />}<span><strong>{item.title}</strong><small>{item.completed_at ? "Concluído" : "Em construção"}</small>{item.description ? <p>{item.description}</p> : null}</span></div>) : <p>Os marcos da construção aparecerão aqui.</p>}</div>;
  const team = <div className={styles.prose}><h2>Quem está construindo</h2>{members.error ? <p role="alert">Não foi possível carregar os integrantes. Recarregue a página.</p> : null}{members.data?.length ? <div className={styles.memberGrid}>{members.data.map(member => { const profile = Array.isArray(member.profiles) ? member.profiles[0] : member.profiles; return <div className={styles.member} key={member.user_id}><strong>{profile?.display_name || "Integrante da equipe"}</strong><span>{member.role_label || "Colaborador"}</span>{profile?.username ? <Link href={`${role === "investor" ? "/investor" : ""}/participants/${encodeURIComponent(profile.username)}`}>@{profile.username}</Link> : null}</div>; })}</div> : <p>{owner}</p>}</div>;
  const code = <div className={styles.prose}><h2><GitBranch size={22} /> Código e demonstrações</h2><p>Acesse as evidências publicadas por quem está construindo.</p>{links.length ? <div className={styles.links}>{links.map(([href, label]) => <a key={href} href={href} target="_blank" rel="noreferrer">{label}<ExternalLink size={16} /></a>)}</div> : <p>Ainda não há links de código ou demonstração.</p>}{canEdit ? <Link className="secondary" href={`/app/projects/${encodeURIComponent(project.slug)}/cockpit`}>Adicionar links</Link> : null}{github.data?.length ? <><h2>Atividade pública do repositório</h2><p>Últimos eventos sincronizados com o GitHub.</p><ol className={styles.timeline}>{github.data.map(event => <li key={event.id}><time>{new Date(event.occurred_at).toLocaleDateString("pt-BR")}</time><div><h3>{event.title}</h3><p>{event.summary}</p>{event.event_html_url ? <a href={event.event_html_url} target="_blank" rel="noreferrer">Ver no GitHub</a> : null}</div></li>)}</ol></> : null}</div>;
  const feedback = <div className={styles.prose}><h2>Conversas sobre o projeto</h2>{posts.error ? <p role="alert">Não foi possível carregar as conversas. Recarregue a página.</p> : null}{posts.data?.length ? posts.data.map(post => <article className={styles.discussion} key={post.id}><time>{new Date(post.created_at).toLocaleDateString("pt-BR")}</time><p>{post.body}</p></article>) : <p>Compartilhe uma atualização vinculada a este projeto para começar a conversa.</p>}<Link className="secondary" href={`${role === "investor" ? "/investor" : ""}/social`}>Abrir publicações e feedback</Link></div>;
  return <ContentTabs label="Conteúdo do projeto" sections={[{ key: "overview", label: "Visão geral", content: overview }, { key: "updates", label: "Atualizações", content: evolution }, { key: "team", label: "Equipe", content: team }, { key: "github", label: "GitHub e links", content: code }, { key: "feedback", label: "Feedback", content: feedback }]} />;
}
